Update news.yaml
chandar-lab/chandar-lab.github.io pull request #56
Opened 2022-05-13 16:50 UTC by goncalomordido

Needs a French-speaking reviewer to check the French text :)

2022-05-14 03:26 UTC, jhuang265 requested changes
Some general comments regarding wording. However since I'm very likely not the best french speaker in the group, feel free to ask others for their opinions.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
>    fr: "Deux papiers accepté à Findings of ACL 2021: [une étude sur l'augmentation de donnée pour le traitement de langage naturel](https://arxiv.org/abs/2105.03075) et [prédiction de lien par moyenne
If you want this to be in past tense, you should write `Deux papiers ont été acceptés` or `Deux papiers acceptés`.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
>    fr: "Notre travail en apprentissage par renforcement pour pour découverte pharmaceutique a été accepté à AAAI 2021."
Typo with two `pour`s. You should also add a `la découverte` since you need the article before the noun.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
> +  fr: "Notre travail à propos de [memory-augmented optimizers](https://openreview.net/pdf?id=NRX9QZ6yqt) a été accepté à ICLR 2022."
I think `memory-augmented optimizers` should have a translation. For example `à propos des optimiseurs augmentés à la mémoire`, although this is definitely very rough and probably not the best.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
> +  fr: "Notre travail à propos de [brown build detection](https://mcis.cs.queensu.ca/publications/2022/icse22.pdf) a été accepté à ICSE 2022."
Maybe use the term `de la détéction des brown builds` since the word `détéction` exists.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
>    fr: "Notre travail à propos de [l'apprentissage continu pour Hanabi](https://arxiv.org/abs/2103.03216) a été accepté à ICML 2021."
Should be `du apprentissage` since `apprentissage` is a masculin noun.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
>    fr: "Deux papiers accepté à Findings of ACL 2021: [une étude sur l'augmentation de donnée pour le traitement de langage naturel](https://arxiv.org/abs/2105.03075) et [prédiction de lien par moyenne
Replace with `l'augmentation des données` and `le traitement du langage naturel`.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
> +  fr: "Notre travail à propos de génération musicale contrainte a été accepté à CP 2022."
I think `de la génération contrainte de la musique` might be better.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
> +  fr: "Notre travail à propos de [perturbation dans NLU](https://arxiv.org/pdf/2107.13955.pdf) a été accepté à Findings of ACL 2022."
`la perturabation`. Also `NLU` might have a french translation since it should be a standard term in NLP.

2022-05-14 03:26 UTC, jhuang265 commented on _data/news.yaml
>    fr: "Notre travail à propos d'une [nouvelle métrique pour le RL basé sur des modèles](https://arxiv.org/abs/2007.03158) a été accepté à NeurIPS 2020."
RL definitely has a french translation that can be used here.

2022-05-14 14:05 UTC, dalafh commented on _data/news.yaml
> +  fr: "Notre travail à propos de génération musicale contrainte a été accepté à CP 2022."
I would go with `Notre travail sur la génération musicale avec contraintes`.

2022-05-14 14:12 UTC, dalafh commented on _data/news.yaml
> +  fr: "Notre travail à propos de [perturbation dans NLU](https://arxiv.org/pdf/2107.13955.pdf) a été accepté à Findings of ACL 2022."
"sur" instead of "à propos de". "À propos de" sounds more formal. Also, NLU seems to be CLN (compréhension du langage naturel) in french but I haven't heard it before. I would suggest "Notre travail sur la perturbation en compréhension du langage naturel" if you have enough space. "CLN/NLU" otherwise in case the french acronym is not well known

2022-05-14 14:18 UTC, dalafh commented on _data/news.yaml
> +  fr: "Notre travail à propos de [memory-augmented optimizers](https://openreview.net/pdf?id=NRX9QZ6yqt) a été accepté à ICLR 2022."
What about `sur les optimiseurs à mémoire augmentée`? Google translate agrees but I couldn't find a technical term.

2022-05-14 14:45 UTC, dalafh commented on _data/news.yaml
> +  fr: "Notre travail à propos de [brown build detection](https://mcis.cs.queensu.ca/publications/2022/icse22.pdf) a été accepté à ICSE 2022."
Again "sur" instead of "à propos". And yes, I agree with "détection". Brown can also be translated to "brun" but build doesn't seem to have a french equivalent. So `sur la détection de builds bruns` should work. I know that's what Doriane used in her masters thesis

2022-05-14 14:45 UTC, dalafh commented on _data/news.yaml
>    fr: "Notre travail à propos de [l'apprentissage continu pour Hanabi](https://arxiv.org/abs/2103.03216) a été accepté à ICML 2021."
Actually, since apprentissage starts with a vowel, "de l'" is correct. This is to avoid saying u + a. Du is a contraction of "de + le" (masculine version of "de + la")

2022-05-14 14:45 UTC, dalafh commented on _data/news.yaml
>    fr: "Deux papiers accepté à Findings of ACL 2021: [une étude sur l'augmentation de donnée pour le traitement de langage naturel](https://arxiv.org/abs/2105.03075) et [prédiction de lien par moyenne
I agree! "ont été acceptés" means "were accepted". "acceptés" means "accepted" (we add the s because papiers is plural). Just a note: "papiers" should be changed to `articles`. I think that "papier" was borrowed from english.

2022-05-14 14:45 UTC, dalafh commented on _data/news.yaml
>    fr: "Deux papiers accepté à Findings of ACL 2021: [une étude sur l'augmentation de donnée pour le traitement de langage naturel](https://arxiv.org/abs/2105.03075) et [prédiction de lien par moyenne
+1

2022-05-14 14:45 UTC, dalafh commented on _data/news.yaml
>    fr: "Notre travail en apprentissage par renforcement pour pour découverte pharmaceutique a été accepté à AAAI 2021."
+1

2022-05-14 14:45 UTC, dalafh commented on _data/news.yaml
>    fr: "Notre travail à propos d'une [nouvelle métrique pour le RL basé sur des modèles](https://arxiv.org/abs/2007.03158) a été accepté à NeurIPS 2020."
Yep, that translation is "apprentissage par renforcement"!

2022-05-14 14:45 UTC, dalafh commented on _data/news.yaml
>    fr: "Le cours de Sarath concernant [une introduction à l'apprentissage machine](https://www.youtube.com/watch?v=snYZF8Dzuwo&list=PLImtCgowF_ET0mi-AmmqQ0SIJUpWYaIOr) est disponible sur Youtube!"
`Le cours de Sarath d'introduction à l'apprentissage automatique`

2022-05-14 17:35 UTC, AndreasMadsen commented
@goncalomordido Thanks for making the PR. And thanks to @jhuang265 and @dalafh for reviewing the French. I will let @goncalomordido update the content.

Once we have a list of "these events should always be news", then I can look into autogenerating some of them. For example, "X paper got published at Y" should be easy. That should reduce the maintenance burden. We could also replace `hidden: bool` with "show the last 10 news" or something like that.

2022-05-16 12:28 UTC, goncalomordido commented
Thank you @jhuang265 and @dalafh! I made the appropriate changes @AndreasMadsen

2022-05-16 15:16 UTC, merged